"""empty message

Revision ID: 9b90d404d4da
Revises: 
Create Date: 2020-01-17 11:29:54.791822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b90d404d4da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('paid_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transaction', 'paid_price')
    # ### end Alembic commands ###
